web:
  # Web监听网卡地址
  address:  0.0.0.0
  # Web监听端口
  port:     9998
  # prometheus监控端口
  monitor_port: 13582

pprof:
  is_open: false
  port: 16660

#mysql配置信息
db:
 host: cm_explorer_db
 port: 3306
 username: root
 password: chainmaker
 #数据库
 database: chainmaker_dquery
 #db类型： ClickHouse / Mysql
 db_provider: Mysql

db_redis:
  #cluster:集群/node：单机
  type: node
  host:
    - redis:6379
  username:
  password: explorer_redis
  prefix: dquery_


#自主查询数据库配置信息（浏览器链存储配置）
chainmaker_db:
  #浏览器链存储数据库
  host: cm_explorer_db
  port: 3306
  #链数据库账户信息，为了数据库安全需要配置成只读账户
  username: root
  password: chainmaker
  #链存储DB
  database: chainmaker_explorer
  #链存储数据库类型，ClickHouse / Mysql/ Pgsql
  db_provider: Mysql
  #sql语句单次查询超时时间，单位秒，超出后自定停止，防止慢查询占用资源
  query_timeout: 300
  #需要查询的链列表，支持多链
  chain_list:
      #链ID
    - chain_id: chainmaker_pk
      #链表的前缀，用来过滤同一个数据库订阅多条链的情况，基本和chain_id保持一致就可以
      prefix: chainmaker_pk
